version: 2

models:
  - name: code_name
    description: table contains code and name of the country
    columns:
      - name: state
        description: code of the state
        tests:
          - not_null
      - name: state_name
        description: name of the state
        tests:
          - not_null
    