
name: 'dbt_miti_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
  - "target"
  - "dbt_packages"

vars:
  names: ['dev', 'prod']
  transform_asian: '`maximal-boulder-389014`.`covid19_transform`.`trf_asian`'