version: 2

models:
  - name: open_data
    description: one record about deaths in countries per year
    columns:
      - name: country_year
      - name: general_deaths
      - name: max_deaths_per_month
      - name: frequency