version: 2

models:
  - name: covid19_deaths_white
    description: one record per date of deaths
    columns:
      - name: date
        description: Date of record
        tests:
          - not_null
      - name: positive_cases_white
        description: Positive cases of the white
        tests:
          - not_null
      - name: deaths_white
        description: Deaths cases of the white
        tests:
          - not_null
             

  - name: covid19_deaths_black
    description: one record per date of deaths
    columns:
      - name: date
        description: Date of record
        tests:
          - not_null       
      - name: positive_cases_black
        description: Positive cases of the black
        tests:
          - not_null
      - name: deaths_black
        description: Deaths cases of the black
        tests:
          - not_null

  - name: covid19_deaths_asian
    description: one record per date of deaths
    columns:
      - name: date
        description: Date of record
        tests:
          - not_null   
      - name: positive_cases_asian
        description: Positive cases of the asian
        tests:
          - not_null
      - name: deaths_asian
        description: Deaths cases of the asian
        tests:
          - not_null